sudo: required
dist: trusty
os: linux
language: minimal
cache:
  apt: true
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - MAKEJOBS=-j5
  - CCACHE_SIZE=400M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks/
  - LASTTAG=$(git describe --tags)
  - TAG="$LASTTAG"
  matrix:
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" MAKEJOBS="-j4" WINE=true
  - HOST=x86_64-pc-linux-gnu PACKAGES="bc python3-zmq zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --disable-tests" CPPFLAGS="-DDEBUG_LOCKORDER -DENABLE_DASH_DEBUG"
  - HOST=arm-linux-gnueabihf DEP_OPTS="NO_QT=1" PACKAGES="g++-arm-linux-gnueabihf libc6-dev-armhf-cross" GOAL="install-strip" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports --disable-tests"
  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc zip unzip libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-reduce-exports --disable-tests"
  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq zip unzip libc6-dev libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --disable-tests LDFLAGS=-static-libstdc++"
  - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" OSX_SDK=10.9 GOAL="deploy"
before_install:
- travis_retry sudo apt-get install python-dev
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |  sed "s|::|:|g")
install:
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
- unset CC; unset CXX
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
- cd $TRAVIS_BUILD_DIR/depends
- make $MAKEJOBS HOST=$HOST $DEP_OPTS
- cd $TRAVIS_BUILD_DIR
- "./autogen.sh"
- CONFIG_SITE=$TRAVIS_BUILD_DIR/depends/$HOST/share/config.site ./configure $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG --prefix=$TRAVIS_BUILD_DIR/../3dcoin-$HOST-$TAG
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
before_deploy:
- if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv 3DCoin-Core.dmg 3DCoin-Core-$TAG-macosx-generic.dmg; FILE=3DCoin-Core-$TAG-macosx-generic.dmg; fi
- if [ "$HOST" == "x86_64-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r 3dcoin-$TAG-win-x64.zip 3dcoin-$HOST-$TAG; mv 3dcoin-$TAG-win-x64.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR; FILE="3dcoin-$TAG-win-x64.zip"; fi
- if [ "$HOST" == "i686-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r 3dcoin-$TAG-win-x32.zip 3dcoin-$HOST-$TAG; mv 3dcoin-$TAG-win-x32.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR; FILE="3dcoin-$TAG-win-x32.zip"; fi
- if [ "$HOST" == "i686-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r 3dcoin-$TAG-$HOST.zip 3dcoin-$HOST-$TAG; mv 3dcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR; FILE="3dcoin-$TAG-$HOST.zip"; fi
- if [ "$HOST" == "x86_64-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r 3dcoin-$TAG-$HOST.zip 3dcoin-$HOST-$TAG; mv 3dcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR; FILE="3dcoin-$TAG-$HOST.zip"; fi
- if [ "$HOST" == "arm-linux-gnueabihf" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r 3dcoin-$TAG-$HOST.zip 3dcoin-$HOST-$TAG; mv 3dcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR; FILE="3dcoin-$TAG-$HOST.zip"; fi
deploy:
  provider: releases
  api_key:
    secure: EE+mLYRe1cEpRrbJ5fEIGpdIalacjhPzbUZGl+Vn1tvmc1EOLjt5xBnRD1WXzWD3aql5XPhNdH2SEJewMwhJWLJCrrS8XjS+SrWLk4ywpRa0y9IcYS0/KuXeIfdAikHlTBrI5OzxM4IB0C4cXE6eSs9ZTS1TVuEU3+6ffR7nsEGnPNTMiJzvP/oh5D+BWD2an34oRCZJJGOecbwQgoySGcnsfw+R7vSOUf5ayAg1Y+XHA71faz2mhUaocMhyLjLg0fRyAe2E8ea4MZcv89zzvDmZFq5LeWfB/fjRnO33akmGbvKKYcFUme1UaZZi8KBWyr7OgvXcwFlIw8arD31ZV1ZXbMtHv0N2KRkSgQnRTJFFQtktMW8XTgmSYqeTipe+/rpHfepDosoZgMPMzCq5H+/xLb02yu0Ezje7O5TtS7bUA1fi7B6ieXro931ca4SxJ7vaw2H7yoJu6YKkHqGOT4evP70mcNCdF3gaAKbK+Wv35jD8/W67Cp0DgLHMDegSXKZHUejAadQ3c5N8QAagroxi91ijiJoFdkjjYSqj+O6wGVGvU5sjNLvJ8MFTx2cyFFVP8MB3O8cM2uXOT1rTkjvaKqAcXvqezsRSqsGZxgold8w9jWVfhXFBSIDk9urxH2AUI4/0JUgqadPRg6/pB+NNBgXmqTYL3CdUmsNeQA8=
  file: "$FILE"
  on:
    repo: ScaMar/3dcoin
    branch: master
    tags: true
  skip_cleanup: true
